package cn.edu.bnu.land.model;

// Generated 2015-12-21 21:22:35 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String username;
	private int userid;
	private String password;
	private boolean enabled;
	private Date registerdate;
	private String truename;
	private String email;
	private String mobilenum;
	private String phonenum;
	private String description;

	public Users() {
	}

	public Users(int userid, String password, boolean enabled) {
		this.userid = userid;
		this.password = password;
		this.enabled = enabled;
	}

	public Users(int userid, String password, boolean enabled,
			Date registerdate, String truename, String email, String mobilenum,
			String phonenum, String description) {
		this.userid = userid;
		this.password = password;
		this.enabled = enabled;
		this.registerdate = registerdate;
		this.truename = truename;
		this.email = email;
		this.mobilenum = mobilenum;
		this.phonenum = phonenum;
		this.description = description;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Date getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(Date registerdate) {
		this.registerdate = registerdate;
	}

	public String getTruename() {
		return this.truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobilenum() {
		return this.mobilenum;
	}

	public void setMobilenum(String mobilenum) {
		this.mobilenum = mobilenum;
	}

	public String getPhonenum() {
		return this.phonenum;
	}

	public void setPhonenum(String phonenum) {
		this.phonenum = phonenum;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
